// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class FirebaseOptions {
  const FirebaseOptions({
    this.apiKey,
    this.appId,
    this.messagingSenderId,
    this.projectId,
    this.authDomain,
    this.storageBucket,
    this.measurementId,
    this.iosBundleId,
  });

  final String? apiKey;
  final String? appId;
  final String? messagingSenderId;
  final String? projectId;
  final String? authDomain;
  final String? storageBucket;
  final String? measurementId;
  final String? iosBundleId;
}

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCagOToIiEvGDNIq0iNzp00gvDhqZNvr4',
    appId: '1:454357064313:web:5fe89cb2ad2e7535c292a8',
    messagingSenderId: '454357064313',
    projectId: 'reddihelp',
    authDomain: 'reddihelp.firebaseapp.com',
    storageBucket: 'reddihelp.firebasestorage.app',
    measurementId: 'G-WYW9F05L03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk4Avy2GIqOddKBOdq6eL7l3RqAUBvjIs',
    appId: '1:454357064313:android:8becaf95bc2fb040c292a8',
    messagingSenderId: '454357064313',
    projectId: 'reddihelp',
    storageBucket: 'reddihelp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4fz54Od2AuLbW6bNKPpKa5bF1cgrLf4g',
    appId: '1:454357064313:ios:687297e500771d12c292a8',
    messagingSenderId: '454357064313',
    projectId: 'reddihelp',
    storageBucket: 'reddihelp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4fz54Od2AuLbW6bNKPpKa5bF1cgrLf4g',
    appId: '1:454357064313:ios:687297e500771d12c292a8',
    messagingSenderId: '454357064313',
    projectId: 'reddihelp',
    storageBucket: 'reddihelp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCagOToIiEvGDNIq0iNzp00gvDhqZNvr4',
    appId: '1:454357064313:web:bd91028fc9439169c292a8',
    messagingSenderId: '454357064313',
    projectId: 'reddihelp',
    authDomain: 'reddihelp.firebaseapp.com',
    storageBucket: 'reddihelp.firebasestorage.app',
    measurementId: 'G-37Q5BLSP1G',
  );
}
